version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nobodyknow
      POSTGRES_DB: community
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: 'no'
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8080:80'
    networks:
        - common
    restart: always
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      DB_HOST: host.docker.internal
      DATABASE_URL: postgres://postgres:nobodyknow@host.docker.internal:5432/community
    networks:
        - common
networks:
    common: